name: Scoop Core CI Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test_powershell:
    name: WindowsPowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: PSScriptAnalyzer, BuildHelpers, Pester:4.10.1
          shell: powershell
      - name: Test Scoop Core
        shell: powershell
        run: ./test/bin/test.ps1
  test_pwsh:
    name: PowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: PSScriptAnalyzer, BuildHelpers, Pester:4.10.1
          shell: pwsh
      - name: Test Scoop Core
        shell: pwsh
        run: ./test/bin/test.ps1
